apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-app-argocd
spec:
  project: development
  source:
    repoURL: https://192.168.56.11.nip.io:8080/root/iot.git
    targetRevision: master
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true