apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: http://gitlab.192.168.56.110.nip.io:8080/root/inception-of-things-p3.git
  password: 
  username: root