apiVersion: v1
kind: Service
metadata:
  name: app2-svc
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: hello-app2
          imagePullPolicy: Always
          image: paulbouwer/hello-kubernetes:1.10
          env:
          - name: MESSAGE
            value: "Hello from app2."
          ports:
            - containerPort: 8080
