# export VAGRANT_HOME="$HOME/goinfre/vagrant"

# local box will be used
# box generic/alpine38 (v4.2.14 currently released version) is downloaded from https://app.vagrantup.com/debian/boxes/bullseye64 (https://app.vagrantup.com/centos/boxes/7)
# as CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box
# than run  [ vagrant box add debian_bullseye64 ~/goinfre/debian_bullseye64   #vagrant box add debian_bullseye64 ~/goinfre/8e272242-fd98-48ff-8309-a12b78ae0ab1  ]
# program output:
# ==> box: Box file was not detected as metadata. Adding it directly...
# ==> box: Adding box 'debian_bullseye64' (v0) for provider:
    # box: Unpacking necessary files from: file:///Users/bgoat/goinfre/8735b8d8-9dfe-402b-8985-de3192b1a1d9
# ==> box: Successfully added box 'debian_bullseye64' (v0) for 'virtualbox'!
# after that [vagrant up] can be used

masterIp="192.168.56.110"
agentIp="192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = "debian_bullseye64"
  config.vm.synced_folder "./shared_files", "/home/vagrant/vagrant", create: true

  id_rsa_pub = File.read("#{ENV['HOME']}/.ssh/id_rsa.pub")
  config.vm.define "bgoatS" do | server |
    server.vm.hostname = "bgoatS"
    server.vm.network "private_network", ip: masterIp
    server.vm.provider "virtualbox" do |v|
      v.name = "bgoatS"
      v.memory = 1024
      v.cpus = 1
    end

    server.vm.provision "shell", privileged: true, inline:  <<-SHELL
      echo '#{id_rsa_pub}' >> /home/vagrant/.ssh/authorized_keys
      sudo apt-get update
      apt-get install curl net-tools -y
      export INSTALL_K3S_EXEC="--bind-address=#{masterIp} --node-external-ip=#{masterIp} --flannel-iface=eth1 --write-kubeconfig-mode 777"
      curl -sfL https://get.k3s.io | sh -
      sleep 5
      cp /var/lib/rancher/k3s/server/node-token /home/vagrant/vagrant
  SHELL
  end

  config.vm.define "cmarshaSW" do | serverWorker |
    serverWorker.vm.hostname = "cmarshaSW"
    serverWorker.vm.network "private_network", ip: agentIp
    serverWorker.vm.provider "virtualbox" do |v|
      v.name = "cmarshaSW"
      v.memory = 1024
      v.cpus = 1
    end

    serverWorker.vm.provision "shell", privileged: true, inline:  <<-SHELL
      echo '#{id_rsa_pub}' >> /home/vagrant/.ssh/authorized_keys
      apt-get update
      apt-get install curl net-tools -y
      export K3S_TOKEN="$(cat /home/vagrant/vagrant/node-token)"
      export K3S_URL=https://#{masterIp}:6443
      export INSTALL_K3S_EXEC="--flannel-iface=eth1"
      curl -sfL https://get.k3s.io | sh -
      sleep 5
    SHELL
  end
    
end

# vagrant halt