# export VAGRANT_HOME="$HOME/goinfre/.vagrant.d"

# local box will be used
# box generic/alpine38 (v4.2.14 currently released version) is downloaded from https://app.vagrantup.com/debian/boxes/bullseye64 (https://app.vagrantup.com/centos/boxes/7)
# as CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box
# than run  [ vagrant box add debian_bullseye64 ~/goinfre/debian_bullseye64   #CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box ]
# program output:
# ==> box: Box file was not detected as metadata. Adding it directly...
# ==> box: Adding box 'debian_bullseye64' (v0) for provider:
    # box: Unpacking necessary files from: file:///Users/bgoat/goinfre/8735b8d8-9dfe-402b-8985-de3192b1a1d9
# ==> box: Successfully added box 'debian_bullseye64' (v0) for 'virtualbox'!
# after that [vagrant up] can be used

masterIp="192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.define "bonusS" do | server |
    server.vm.box = "debian_bullseye64"
    server.vm.synced_folder "./confs", "/home/vagrant/confs"
    server.vm.synced_folder "./scripts", "/home/vagrant/scripts"

    config.vm.network "forwarded_port", guest: 8080, host: 8480
    config.vm.network "forwarded_port", guest: 8888, host: 8488
    config.vm.network "forwarded_port", guest: 8400, host: 8400
    config.vm.network "forwarded_port", guest: 8443, host: 9443
    
    config.vm.hostname = "bgoatS"
    server.vm.network "private_network", ip: masterIp
    server.vm.provider "virtualbox" do |v|
      v.name = "bonusS"
      v.memory = 8192
      v.cpus = 6
    end

    config.vm.provision "script", type: "shell", privileged: true, path: "./scripts/setup.sh"
  end
    
end
